version: '3.7'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dreamjob

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"